name: Laravel project master update

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REMOTE_HOST: ''
  REMOTE_HOST_PORT: ''
  REMOTE_USER: ''
  TARGET_DIRECTORY: ''
jobs:
  project-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: |
          echo GH_CARBON_SECRET
          echo "${{ env.GH_CARBON_SECRET }}"
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 195.210.46.94
          server-dir: lara.carbonfiber.kz/
          username: carbonfi
          password: ${{ secrets.DEPLOY_CARBON_SECRET }}
  project-update:
    runs-on: self-hosted
    needs: 'project-upload'
    steps:
      - name: Clear cash and composer update
        run: ACTIONS_RUNNER_HOOK_JOB_COMPLETED=/cleanup.sh
